export * from './enroll-student.dto';
export * from './enroll-course.dto';
export * from './assign-professor.dto';
export * from './register-exam.dto';
export * from './create-exam-period.dto';
export * from './create-exam.dto';
export * from './grade-exam.dto';
export * from './search-students.dto';
export * from './update-enrollment.dto';
